/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type deMessage from '../locales/de/messages.json';
import type esMessage from '../locales/es/messages.json';
import type frMessage from '../locales/fr/messages.json';
import type pt_BRMessage from '../locales/pt_BR/messages.json';
import type ruMessage from '../locales/ru/messages.json';
import type zh_TWMessage from '../locales/zh_TW/messages.json';

export type MessageKey = keyof typeof enMessage &
  keyof typeof deMessage &
  keyof typeof esMessage &
  keyof typeof frMessage &
  keyof typeof pt_BRMessage &
  keyof typeof ruMessage &
  keyof typeof zh_TWMessage;

export type DevLocale = 'en' | 'de' | 'es' | 'fr' | 'pt_BR' | 'ru' | 'zh_TW';
